# Site settings
title: Mooqoo's blog
email: mooqooapp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mooqoo
github_username:  mooqoo

# Build settings
markdown: kramdown
port:    4040

# About/contact
author:
  name:              mooqoo
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             0.0.1
mygithub:            https://github.com/mooqoo

# Conversion
excerpt_separator: "<!--excerpt-->"